### ISSUE TITLE
The server does not send trees to the client correctly on voxelmap

### ISSUE THREAD

**Issue by okx-code** [CivPlatform/map-sync#20]
![image](https://user-images.githubusercontent.com/17044350/170730343-bb3ac8a2-fd1e-468b-bf10-3c8fc9545c48.png)
![image](https://user-images.githubusercontent.com/17044350/170730354-7f3b079f-67e7-418b-bb53-4a2dedd1ed94.png)

**Comment by Gjum** [comment]
relevant code https://github.com/CivPlatform/map-sync/blob/master/mod/common/src/main/java/gjum/minecraft/mapsync/common/integration/VoxelMapHelperReal.java#L122

**Comment by Gjum** [comment]
"fixed" in 8fa24f4
